version: '3.8'

services:
  options-analyzer:
    build: .
    ports:
      - "3001:3001"
    environment:
      - POLYGON_API_KEY=WxoSPY6czjweSx5etNSSF82S7tps0Nfn
      - NODE_ENV=production
    restart: unless-stopped